# Generated by Django 3.2.17 on 2023-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Organization_Size',
            field=models.CharField(choices=[('100', '100'), ('100-1000', '100-1000'), ('1000 - 10000', '1000 - 10000'),
                                            ('10000', '10000')], default='Organization Size', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_stage',
            field=models.CharField(
                choices=[('Choose Career Stage', 'Choose Career Stage'), ('junior', 'junior'), ('middle', 'middle'),
                         ('senior', 'senior')], default='Choose Career Stage', max_length=25),
        ),
    ]
