# Generated by Django 4.1.5 on 2023-01-30 08:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profile', '0003_alter_profile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='Organization_Size',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior Level', 'Junior Level'), ('Middle Level', 'Middle Level'), ('Senior Level', 'Senior Level')], default='Organization Size', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_stage',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior Level', 'Junior Level'), ('Middle Level', 'Middle Level'), ('Senior Level', 'Senior Level')], default='Choose Career Stage', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='countries',
            field=django_countries.fields.CountryField(default='Choose Country', max_length=746, multiple=True),
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profile.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.industry')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.domain'),
        ),
        migrations.AddField(
            model_name='profile',
            name='function',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.function'),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.industry'),
        ),
    ]
