# Generated by Django 4.1.5 on 2023-01-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_customuser_function_industry_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
