# Generated by Django 4.1.5 on 2023-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Organization_Size',
            field=models.CharField(choices=[('Choose Organization Size', 'Choose Organization Size'), ('Entry Level', 'Entry Level'), ('Junior Level', 'Junior Level'), ('Middle Level', 'Middle Level'), ('Senior Level', 'Senior Level')], default='Organization Size', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_stage',
            field=models.CharField(choices=[('Choose Career Stage', 'Choose Career Stage'), ('Entry Level', 'Entry Level'), ('Junior Level', 'Junior Level'), ('Middle Level', 'Middle Level'), ('Senior Level', 'Senior Level')], default='Choose Career Stage', max_length=25),
        ),
    ]
