# Generated by Django 3.2.17 on 2023-02-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user',)},
        ),
    ]
