# Generated by Django 4.1.5 on 2023-01-30 09:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_profile_organization_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
