# Generated by Django 3.2.17 on 2023-02-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('user',)},
        ),
    ]
