# Generated by Django 3.2.17 on 2023-02-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_otp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
