# Generated by Django 3.2.17 on 2023-02-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20230215_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
