# Generated by Django 4.1.5 on 2023-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_alter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
