# Generated by Django 3.2.17 on 2023-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(),
        ),
    ]
