# Generated by Django 4.1.5 on 2023-01-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_alter_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.industry'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.domain'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.function'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.industry'),
        ),
    ]
