# Generated by Django 4.1.5 on 2023-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_alter_domain_industry_alter_profile_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Organization_Size',
            field=models.CharField(choices=[('Organization Size', 'Organization Size'), ('Entry Level', 'Entry Level'), ('Junior Level', 'Junior Level'), ('Middle Level', 'Middle Level'), ('Senior Level', 'Senior Level')], default='Organization Size', max_length=25),
        ),
    ]
