# Generated by Django 4.1.5 on 2023-01-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_alter_profile_organization_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
