# Generated by Django 4.1.5 on 2023-01-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_alter_profile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.industry'),
        ),
    ]
