# Generated by Django 3.2.17 on 2023-04-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situation', '0002_alter_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='situation.postsituation'),
        ),
    ]
