# Generated by Django 3.2.17 on 2023-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation', '0003_invite_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('invited', 'invited'), ('accepted', 'accepted')], default='invite', max_length=50),
        ),
    ]
