# Generated by Django 3.2.17 on 2023-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation', '0005_auto_20230406_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('invited', 'invited'), ('willing to advised', 'willing to advised'), ('accepted', 'accepted')], default='invite', max_length=50),
        ),
    ]
